-- Práxis Online 0.10.7
-- Para novas instalações. Em bancos existentes, execute primeiro
-- supabase/migrations/20260724_fix_received_at_timestamptz.sql.

create extension if not exists pgcrypto;

do $$ begin
  create type public.praxis_role as enum ('admin', 'procurador', 'assessor', 'consulta');
exception when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.workspace_members (
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.praxis_role not null default 'consulta',
  active boolean not null default true,
  historico_disponivel_desde date,
  created_at timestamptz not null default now(),
  primary key (workspace_id, user_id)
);

create table if not exists public.cases (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  mp_number text not null default '',
  judicial_number text not null,
  class_name text not null default '',
  subject text not null default '',
  socially_relevant boolean not null default false,
  extremely_complex boolean not null default false,
  social_theme text not null default '',
  relevance_reason text not null default '',
  fundamental_right text not null default '',
  affected_group text not null default '',
  reach text not null default '',
  territorial_scope text not null default '',
  impact_type text not null default '',
  social_result text not null default '',
  sdgs text[] not null default '{}'::text[],
  complexity_reason text not null default '',
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, judicial_number)
);

create table if not exists public.movements (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  case_id bigint not null references public.cases(id) on delete cascade,
  received_at timestamptz not null,
  received_time_precise boolean not null default false,
  deadline_at date,
  draft_status text not null default 'Pendente',
  workflow_status text not null default 'Recebido' check (workflow_status in ('Recebido', 'Em análise', 'Minutado', 'Enviado', 'Sobrestado')),
  sent_at timestamptz,
  sent_time_precise boolean not null default false,
  action_type text not null default '',
  notes text not null default '',
  priority text not null default 'Normal' check (priority in ('Baixa', 'Normal', 'Alta', 'Urgente')),
  document_path text not null default '',
  elapsed_hours numeric,
  deleted_at timestamptz,
  archived_at timestamptz,
  row_version integer not null default 1,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.class_settings (
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  name text not null,
  business_days integer not null check (business_days between 1 and 365),
  primary key (workspace_id, name)
);

create table if not exists public.calendar_exclusions (
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  date date not null,
  label text not null,
  primary key (workspace_id, date)
);

create table if not exists public.change_history (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  movement_id bigint not null references public.movements(id) on delete cascade,
  changed_by uuid references auth.users(id),
  changed_at timestamptz not null default now(),
  actor_name text not null default '',
  action_name text not null default 'Alteração',
  field_name text not null,
  old_value text not null default '',
  new_value text not null default ''
);

create index if not exists movements_workspace_received_idx on public.movements(workspace_id, received_at desc);
create index if not exists movements_workspace_status_idx on public.movements(workspace_id, workflow_status);
create index if not exists movements_workspace_deleted_idx on public.movements(workspace_id, deleted_at);
create index if not exists cases_workspace_judicial_idx on public.cases(workspace_id, judicial_number);

create or replace function public.is_workspace_member(target_workspace uuid)
returns boolean language sql stable security definer set search_path = public
as $$ select exists (
  select 1 from public.workspace_members
  where workspace_id = target_workspace and user_id = auth.uid() and active
) $$;

create or replace function public.can_write_workspace(target_workspace uuid)
returns boolean language sql stable security definer set search_path = public
as $$ select exists (
  select 1 from public.workspace_members
  where workspace_id = target_workspace and user_id = auth.uid() and active
    and role in ('admin', 'procurador', 'assessor')
) $$;

create or replace function public.is_workspace_admin(target_workspace uuid)
returns boolean language sql stable security definer set search_path = public
as $$ select exists (
  select 1 from public.workspace_members
  where workspace_id = target_workspace and user_id = auth.uid() and active and role = 'admin'
) $$;

create or replace function public.handle_new_praxis_user()
returns trigger language plpgsql security definer set search_path = public
as $$
declare new_workspace uuid;
begin
  insert into public.profiles(id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''))
  on conflict (id) do nothing;

  insert into public.workspaces(name, created_by)
  values (coalesce(nullif(new.raw_user_meta_data ->> 'full_name', ''), split_part(new.email, '@', 1)) || ' — Práxis', new.id)
  returning id into new_workspace;

  insert into public.workspace_members(workspace_id, user_id, role)
  values (new_workspace, new.id, 'admin');

  insert into public.class_settings(workspace_id, name, business_days) values
    (new_workspace, 'Apelação Cível', 30),
    (new_workspace, 'Agravo de Instrumento', 30),
    (new_workspace, 'Agravo Interno', 30),
    (new_workspace, 'Remessa Necessária', 30),
    (new_workspace, 'Mandado de Segurança', 5),
    (new_workspace, 'Conflito Negativo de Competência', 5),
    (new_workspace, 'Conflito de Competência', 5),
    (new_workspace, 'Recurso Especial', 30),
    (new_workspace, 'Recurso Extraordinário', 30),
    (new_workspace, 'Outro', 30);
  return new;
end $$;

drop trigger if exists on_auth_user_created_praxis on auth.users;
create trigger on_auth_user_created_praxis
after insert on auth.users for each row execute procedure public.handle_new_praxis_user();


create or replace function public.default_missing_sent_at()
returns trigger language plpgsql set search_path = public
as $$
begin
  if new.workflow_status = 'Enviado' and new.sent_at is null then
    new.sent_at := new.received_at + interval '10 days';
    new.sent_time_precise := false;
  end if;
  return new;
end $$;

drop trigger if exists default_missing_sent_at_trigger on public.movements;
create trigger default_missing_sent_at_trigger
before insert or update of workflow_status, sent_at, received_at on public.movements
for each row execute function public.default_missing_sent_at();

create or replace function public.sync_member_historical_coverage()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if new.assigned_to is not null then
    update public.workspace_members
       set historico_disponivel_desde = least(
         coalesce(historico_disponivel_desde, (new.received_at at time zone 'America/Belem')::date),
         (new.received_at at time zone 'America/Belem')::date
       )
     where workspace_id = new.workspace_id and user_id = new.assigned_to;
  end if;
  return new;
end $$;

drop trigger if exists sync_member_historical_coverage_trigger on public.movements;
create trigger sync_member_historical_coverage_trigger
after insert or update of assigned_to, received_at on public.movements
for each row execute function public.sync_member_historical_coverage();

alter table public.profiles enable row level security;
alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.cases enable row level security;
alter table public.movements enable row level security;
alter table public.class_settings enable row level security;
alter table public.calendar_exclusions enable row level security;
alter table public.change_history enable row level security;

drop policy if exists profiles_select_self on public.profiles;
create policy profiles_select_self on public.profiles for select using (id = auth.uid());
drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists workspaces_select_member on public.workspaces;
create policy workspaces_select_member on public.workspaces for select using (public.is_workspace_member(id));
drop policy if exists workspaces_update_admin on public.workspaces;
create policy workspaces_update_admin on public.workspaces for update using (public.is_workspace_admin(id));

drop policy if exists members_select_member on public.workspace_members;
create policy members_select_member on public.workspace_members for select using (public.is_workspace_member(workspace_id));
drop policy if exists members_insert_admin on public.workspace_members;
create policy members_insert_admin on public.workspace_members for insert with check (public.is_workspace_admin(workspace_id));
drop policy if exists members_update_admin on public.workspace_members;
create policy members_update_admin on public.workspace_members for update using (public.is_workspace_admin(workspace_id));
drop policy if exists members_delete_admin on public.workspace_members;
create policy members_delete_admin on public.workspace_members for delete using (public.is_workspace_admin(workspace_id));

drop policy if exists cases_select_member on public.cases;
create policy cases_select_member on public.cases for select using (public.is_workspace_member(workspace_id));
drop policy if exists cases_insert_writer on public.cases;
create policy cases_insert_writer on public.cases for insert with check (public.can_write_workspace(workspace_id));
drop policy if exists cases_update_writer on public.cases;
create policy cases_update_writer on public.cases for update using (public.can_write_workspace(workspace_id));
drop policy if exists cases_delete_admin on public.cases;
create policy cases_delete_admin on public.cases for delete using (public.is_workspace_admin(workspace_id));

drop policy if exists movements_select_member on public.movements;
create policy movements_select_member on public.movements for select using (public.is_workspace_member(workspace_id));
drop policy if exists movements_insert_writer on public.movements;
create policy movements_insert_writer on public.movements for insert with check (public.can_write_workspace(workspace_id));
drop policy if exists movements_update_writer on public.movements;
create policy movements_update_writer on public.movements for update using (public.can_write_workspace(workspace_id));
drop policy if exists movements_delete_admin on public.movements;
create policy movements_delete_admin on public.movements for delete using (public.is_workspace_admin(workspace_id));

drop policy if exists classes_select_member on public.class_settings;
create policy classes_select_member on public.class_settings for select using (public.is_workspace_member(workspace_id));
drop policy if exists classes_insert_writer on public.class_settings;
create policy classes_insert_writer on public.class_settings for insert with check (public.can_write_workspace(workspace_id));
drop policy if exists classes_update_writer on public.class_settings;
create policy classes_update_writer on public.class_settings for update using (public.can_write_workspace(workspace_id));
drop policy if exists classes_delete_admin on public.class_settings;
create policy classes_delete_admin on public.class_settings for delete using (public.is_workspace_admin(workspace_id));

drop policy if exists calendar_select_member on public.calendar_exclusions;
create policy calendar_select_member on public.calendar_exclusions for select using (public.is_workspace_member(workspace_id));
drop policy if exists calendar_insert_writer on public.calendar_exclusions;
create policy calendar_insert_writer on public.calendar_exclusions for insert with check (public.can_write_workspace(workspace_id));
drop policy if exists calendar_update_writer on public.calendar_exclusions;
create policy calendar_update_writer on public.calendar_exclusions for update using (public.can_write_workspace(workspace_id));
drop policy if exists calendar_delete_writer on public.calendar_exclusions;
create policy calendar_delete_writer on public.calendar_exclusions for delete using (public.can_write_workspace(workspace_id));

drop policy if exists history_select_member on public.change_history;
create policy history_select_member on public.change_history for select using (public.is_workspace_member(workspace_id));
drop policy if exists history_insert_writer on public.change_history;
create policy history_insert_writer on public.change_history for insert with check (public.can_write_workspace(workspace_id));
