-- Práxis Online 0.5.0 — segurança, convite obrigatório, MFA administrativo e auditoria
-- Execute uma única vez após 005-qualidade-responsavel-e-data-envio.sql.

create or replace function public.is_workspace_admin(target_workspace uuid)
returns boolean language sql stable security definer set search_path = public
as $$ select exists (
  select 1 from public.workspace_members
  where workspace_id = target_workspace and user_id = auth.uid() and active and role = 'admin'
) and coalesce(auth.jwt() ->> 'aal', 'aal1') = 'aal2' $$;

create or replace function public.shares_workspace_with(target_user uuid)
returns boolean language sql stable security definer set search_path = public
as $$ select exists (
  select 1 from public.workspace_members mine join public.workspace_members theirs on theirs.workspace_id = mine.workspace_id
  where mine.user_id = auth.uid() and mine.active and theirs.user_id = target_user and theirs.active
) $$;
drop policy if exists profiles_select_team on public.profiles;
create policy profiles_select_team on public.profiles for select using (id = auth.uid() or public.shares_workspace_with(id));

-- Qualquer perfil operacional pode redistribuir a carga; consulta permanece somente leitura.
create or replace function public.protect_movement_assignment()
returns trigger language plpgsql security definer set search_path = public
as $$
declare actor uuid := auth.uid();
begin
  if tg_op = 'INSERT' and new.assigned_to is null then new.assigned_to := actor; end if;
  if new.assigned_to is null then raise exception 'O processo precisa ter um responsável'; end if;
  if not exists (select 1 from public.workspace_members where workspace_id = new.workspace_id and user_id = new.assigned_to and active)
    then raise exception 'O responsável deve ser um usuário ativo desta equipe'; end if;
  if actor is not null and not public.can_write_workspace(new.workspace_id)
    then raise exception 'Seu perfil não pode distribuir processos'; end if;
  return new;
end $$;

-- Configurações são administrativas no banco, não apenas no menu.
drop policy if exists classes_insert_writer on public.class_settings;
drop policy if exists classes_update_writer on public.class_settings;
drop policy if exists classes_insert_admin on public.class_settings;
drop policy if exists classes_update_admin on public.class_settings;
create policy classes_insert_admin on public.class_settings for insert with check (public.is_workspace_admin(workspace_id));
create policy classes_update_admin on public.class_settings for update using (public.is_workspace_admin(workspace_id)) with check (public.is_workspace_admin(workspace_id));

drop policy if exists calendar_insert_writer on public.calendar_exclusions;
drop policy if exists calendar_update_writer on public.calendar_exclusions;
drop policy if exists calendar_delete_writer on public.calendar_exclusions;
drop policy if exists calendar_insert_admin on public.calendar_exclusions;
drop policy if exists calendar_update_admin on public.calendar_exclusions;
drop policy if exists calendar_delete_admin on public.calendar_exclusions;
create policy calendar_insert_admin on public.calendar_exclusions for insert with check (public.is_workspace_admin(workspace_id));
create policy calendar_update_admin on public.calendar_exclusions for update using (public.is_workspace_admin(workspace_id)) with check (public.is_workspace_admin(workspace_id));
create policy calendar_delete_admin on public.calendar_exclusions for delete using (public.is_workspace_admin(workspace_id));

-- A lixeira é operacional: escritores podem restaurar e excluir definitivamente uma movimentação.
drop policy if exists movements_delete_admin on public.movements;
drop policy if exists movements_delete_writer on public.movements;
create policy movements_delete_writer on public.movements for delete using (public.can_write_workspace(workspace_id));

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists admin_audit_workspace_created_idx on public.admin_audit_log(workspace_id, created_at desc);
alter table public.admin_audit_log enable row level security;
drop policy if exists admin_audit_select_admin on public.admin_audit_log;
create policy admin_audit_select_admin on public.admin_audit_log for select using (public.is_workspace_admin(workspace_id));

create or replace function public.record_admin_audit(audit_event text, audit_details jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path = public
as $$
declare target_workspace uuid;
begin
  select current_workspace_id into target_workspace from public.profiles where id = auth.uid();
  if target_workspace is null or not public.is_workspace_admin(target_workspace) then raise exception 'Acesso administrativo e segundo fator necessários'; end if;
  insert into public.admin_audit_log(workspace_id, actor_id, event_type, details) values (target_workspace, auth.uid(), audit_event, coalesce(audit_details, '{}'::jsonb));
end $$;

create or replace function public.list_admin_audit()
returns table(id bigint, created_at timestamptz, event_type text, actor_name text, actor_email text, details jsonb)
language plpgsql stable security definer set search_path = public
as $$
declare target_workspace uuid;
begin
  select current_workspace_id into target_workspace from public.profiles where profiles.id = auth.uid();
  if target_workspace is null or not public.is_workspace_admin(target_workspace) then raise exception 'Acesso administrativo e segundo fator necessários'; end if;
  return query select a.id, a.created_at, a.event_type, coalesce(p.full_name, ''), coalesce(u.email, ''), a.details
  from public.admin_audit_log a left join public.profiles p on p.id = a.actor_id left join auth.users u on u.id = a.actor_id
  where a.workspace_id = target_workspace order by a.created_at desc limit 500;
end $$;

create or replace function public.audit_admin_table_change()
returns trigger language plpgsql security definer set search_path = public
as $$
declare target_workspace uuid; payload jsonb;
begin
  target_workspace := coalesce((to_jsonb(new) ->> 'workspace_id')::uuid, (to_jsonb(old) ->> 'workspace_id')::uuid);
  payload := jsonb_build_object('table', tg_table_name, 'operation', tg_op);
  if tg_table_name = 'class_settings' then payload := payload || jsonb_build_object('name', coalesce(new.name, old.name)); end if;
  if tg_table_name = 'calendar_exclusions' then payload := payload || jsonb_build_object('date', coalesce(new.date, old.date)); end if;
  insert into public.admin_audit_log(workspace_id, actor_id, event_type, details)
  values (target_workspace, auth.uid(), case when tg_table_name = 'class_settings' then 'class_setting_changed' else 'calendar_changed' end, payload);
  return null;
end $$;

drop trigger if exists audit_class_settings on public.class_settings;
create trigger audit_class_settings after insert or update or delete on public.class_settings for each row execute function public.audit_admin_table_change();
drop trigger if exists audit_calendar_exclusions on public.calendar_exclusions;
create trigger audit_calendar_exclusions after insert or update or delete on public.calendar_exclusions for each row execute function public.audit_admin_table_change();

-- Validação prévia do convite, inclusive antes da autenticação.
create or replace function public.validate_workspace_invite(invited_email text, invite_token text)
returns boolean language sql stable security definer set search_path = public
as $$ select exists (
  select 1 from public.workspace_invites
  where email = lower(trim(invited_email))
    and token_hash = encode(extensions.digest(upper(trim(invite_token)), 'sha256'), 'hex')
    and accepted_at is null and expires_at > now()
) $$;
grant execute on function public.validate_workspace_invite(text, text) to anon, authenticated;

create or replace function public.create_workspace_invite(invited_email text, invited_role public.praxis_role)
returns text language plpgsql security definer set search_path = public
as $$
declare target_workspace uuid; raw_token text;
begin
  select current_workspace_id into target_workspace from public.profiles where id = auth.uid();
  if target_workspace is null or not public.is_workspace_admin(target_workspace) then raise exception 'Somente o administrador com segundo fator pode criar convites'; end if;
  if invited_role = 'admin' then raise exception 'O convite não pode conceder administração'; end if;
  raw_token := upper(encode(extensions.gen_random_bytes(6), 'hex'));
  insert into public.workspace_invites(workspace_id, email, role, token_hash, created_by)
  values (target_workspace, lower(trim(invited_email)), invited_role, encode(extensions.digest(raw_token, 'sha256'), 'hex'), auth.uid());
  insert into public.admin_audit_log(workspace_id, actor_id, event_type, details)
  values (target_workspace, auth.uid(), 'invite_created', jsonb_build_object('email', lower(trim(invited_email)), 'role', invited_role));
  return raw_token;
end $$;

create or replace function public.update_workspace_member(target_user uuid, new_role public.praxis_role, new_active boolean)
returns void language plpgsql security definer set search_path = public
as $$
declare target_workspace uuid;
begin
  select current_workspace_id into target_workspace from public.profiles where id = auth.uid();
  if not public.is_workspace_admin(target_workspace) then raise exception 'Acesso administrativo e segundo fator necessários'; end if;
  if target_user = auth.uid() then raise exception 'O administrador não pode alterar o próprio acesso'; end if;
  if new_role = 'admin' then raise exception 'A promoção para administrador exige procedimento específico'; end if;
  update public.workspace_members set role = new_role, active = new_active where workspace_id = target_workspace and user_id = target_user;
  insert into public.admin_audit_log(workspace_id, actor_id, event_type, details)
  values (target_workspace, auth.uid(), 'member_updated', jsonb_build_object('target_user', target_user, 'role', new_role, 'active', new_active));
end $$;

-- Novas contas não criam gabinetes próprios: só recebem acesso ao aceitar convite.
create or replace function public.handle_new_praxis_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles(id, full_name) values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', '')) on conflict (id) do nothing;
  return new;
end $$;

comment on table public.admin_audit_log is 'Eventos administrativos sensíveis do Práxis; leitura exige papel admin e sessão AAL2.';
