-- Práxis Online 0.11.3-RC
-- Central de Informações + Web Push, arquiteturalmente desacoplados da contingência.
-- A Central é persistente no PostgreSQL. A entrega Push usa fila própria e Edge Function.

begin;

create extension if not exists pg_net;

-- ============================================================
-- 1. PREFERÊNCIAS DE NOTIFICAÇÃO
-- ============================================================

create table if not exists public.notification_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  push_enabled boolean not null default true,
  push_assignments boolean not null default true,
  push_transfers boolean not null default true,
  push_status boolean not null default false,
  push_deadlines boolean not null default false,
  updated_at timestamptz not null default now()
);

alter table public.notification_preferences enable row level security;
revoke all on public.notification_preferences from anon, authenticated;

-- ============================================================
-- 2. CENTRAL DE INFORMAÇÕES
-- ============================================================

create table if not exists public.user_notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  workspace_name text not null default '',
  notification_type text not null check (notification_type in ('assignment','transfer','status','deadline','system')),
  severity text not null default 'info' check (severity in ('info','success','warning','urgent')),
  title text not null,
  body text not null default '',
  movement_id bigint references public.movements(id) on delete set null,
  process_number text not null default '',
  actor_user_id uuid references auth.users(id) on delete set null,
  push_requested boolean not null default false,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);

create index if not exists user_notifications_recipient_created_idx
  on public.user_notifications(recipient_user_id, created_at desc);
create index if not exists user_notifications_recipient_unread_idx
  on public.user_notifications(recipient_user_id, created_at desc)
  where read_at is null;
create index if not exists user_notifications_workspace_idx
  on public.user_notifications(workspace_id, created_at desc);

alter table public.user_notifications enable row level security;
revoke all on public.user_notifications from anon, authenticated;
grant select on public.user_notifications to authenticated;

 drop policy if exists user_notifications_select_self_v0113 on public.user_notifications;
create policy user_notifications_select_self_v0113
  on public.user_notifications for select
  to authenticated
  using (recipient_user_id = auth.uid());

-- Realtime somente entrega linhas que a própria RLS permite visualizar.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime' and not puballtables)
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'user_notifications'
     ) then
    execute 'alter publication supabase_realtime add table public.user_notifications';
  end if;
end $$;

-- ============================================================
-- 3. ASSINATURAS WEB PUSH
-- ============================================================

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth_secret text not null,
  user_agent text not null default '',
  enabled boolean not null default true,
  failure_count integer not null default 0,
  last_error text not null default '',
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_enabled_idx
  on public.push_subscriptions(user_id, enabled);

alter table public.push_subscriptions enable row level security;
revoke all on public.push_subscriptions from anon, authenticated;

-- ============================================================
-- 4. FILA DE ENTREGA PUSH
-- ============================================================

create table if not exists public.push_deliveries (
  id bigint generated by default as identity primary key,
  notification_id uuid not null references public.user_notifications(id) on delete cascade,
  subscription_id uuid not null references public.push_subscriptions(id) on delete cascade,
  state text not null default 'queued' check (state in ('queued','processing','sent','failed')),
  attempts integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  claimed_at timestamptz,
  sent_at timestamptz,
  last_error text not null default '',
  created_at timestamptz not null default now(),
  unique(notification_id, subscription_id)
);

create index if not exists push_deliveries_queue_idx
  on public.push_deliveries(state, next_attempt_at, id)
  where state in ('queued','processing');

alter table public.push_deliveries enable row level security;
revoke all on public.push_deliveries from anon, authenticated;

-- Runtime privado. O token é gerado no banco e nunca é exposto aos clientes.
create table if not exists public.push_runtime_v0113 (
  singleton boolean primary key default true check (singleton),
  dispatch_url text not null,
  dispatch_token uuid not null default gen_random_uuid(),
  updated_at timestamptz not null default now()
);

alter table public.push_runtime_v0113 enable row level security;
revoke all on public.push_runtime_v0113 from anon, authenticated;

insert into public.push_runtime_v0113(singleton, dispatch_url)
values(true, 'https://yoqsxkakoeqjbiaewdim.supabase.co/functions/v1/push-dispatch')
on conflict(singleton) do update
set dispatch_url = excluded.dispatch_url,
    updated_at = now();

-- ============================================================
-- 5. RPCs DE PREFERÊNCIAS E DISPOSITIVO
-- ============================================================

create or replace function public.get_notification_preferences_v0113()
returns table(
  push_enabled boolean,
  push_assignments boolean,
  push_transfers boolean,
  push_status boolean,
  push_deadlines boolean
)
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.notification_preferences(user_id)
  values(auth.uid())
  on conflict(user_id) do nothing;

  return query
  select p.push_enabled, p.push_assignments, p.push_transfers, p.push_status, p.push_deadlines
  from public.notification_preferences p
  where p.user_id = auth.uid();
end
$$;

create or replace function public.save_notification_preferences_v0113(
  new_push_enabled boolean,
  new_push_assignments boolean,
  new_push_transfers boolean,
  new_push_status boolean,
  new_push_deadlines boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Sessão inválida.'; end if;
  insert into public.notification_preferences(
    user_id, push_enabled, push_assignments, push_transfers, push_status, push_deadlines, updated_at
  ) values(
    auth.uid(), coalesce(new_push_enabled,true), coalesce(new_push_assignments,true),
    coalesce(new_push_transfers,true), coalesce(new_push_status,false),
    coalesce(new_push_deadlines,false), now()
  )
  on conflict(user_id) do update set
    push_enabled = excluded.push_enabled,
    push_assignments = excluded.push_assignments,
    push_transfers = excluded.push_transfers,
    push_status = excluded.push_status,
    push_deadlines = excluded.push_deadlines,
    updated_at = now();
end
$$;

create or replace function public.upsert_push_subscription_v0113(
  subscription_endpoint text,
  subscription_p256dh text,
  subscription_auth text,
  subscription_user_agent text default ''
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare subscription_id uuid;
begin
  if auth.uid() is null then raise exception 'Sessão inválida.'; end if;
  if length(trim(coalesce(subscription_endpoint,''))) < 20 then raise exception 'Assinatura Push inválida.'; end if;
  if trim(coalesce(subscription_p256dh,'')) = '' or trim(coalesce(subscription_auth,'')) = '' then
    raise exception 'Chaves da assinatura Push não informadas.';
  end if;

  insert into public.push_subscriptions(
    user_id, endpoint, p256dh, auth_secret, user_agent, enabled, failure_count, last_error, last_seen_at, updated_at
  ) values(
    auth.uid(), subscription_endpoint, subscription_p256dh, subscription_auth,
    left(coalesce(subscription_user_agent,''), 500), true, 0, '', now(), now()
  )
  on conflict(endpoint) do update set
    user_id = auth.uid(),
    p256dh = excluded.p256dh,
    auth_secret = excluded.auth_secret,
    user_agent = excluded.user_agent,
    enabled = true,
    failure_count = 0,
    last_error = '',
    last_seen_at = now(),
    updated_at = now()
  returning id into subscription_id;

  return subscription_id;
end
$$;

create or replace function public.remove_push_subscription_v0113(subscription_endpoint text)
returns void
language sql
security definer
set search_path = public
as $$
  update public.push_subscriptions
     set enabled = false, updated_at = now()
   where endpoint = subscription_endpoint and user_id = auth.uid()
$$;

create or replace function public.count_my_push_subscriptions_v0113()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select count(*)::integer
  from public.push_subscriptions
  where user_id = auth.uid() and enabled
$$;

create or replace function public.mark_notification_read_v0113(target_notification uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update public.user_notifications
     set read_at = coalesce(read_at, now())
   where id = target_notification and recipient_user_id = auth.uid()
$$;

create or replace function public.mark_all_notifications_read_v0113()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare changed integer;
begin
  update public.user_notifications
     set read_at = now()
   where recipient_user_id = auth.uid() and read_at is null;
  get diagnostics changed = row_count;
  return changed;
end
$$;

revoke execute on function public.get_notification_preferences_v0113() from public, anon;
revoke execute on function public.save_notification_preferences_v0113(boolean,boolean,boolean,boolean,boolean) from public, anon;
revoke execute on function public.upsert_push_subscription_v0113(text,text,text,text) from public, anon;
revoke execute on function public.remove_push_subscription_v0113(text) from public, anon;
revoke execute on function public.count_my_push_subscriptions_v0113() from public, anon;
revoke execute on function public.mark_notification_read_v0113(uuid) from public, anon;
revoke execute on function public.mark_all_notifications_read_v0113() from public, anon;

grant execute on function public.get_notification_preferences_v0113() to authenticated;
grant execute on function public.save_notification_preferences_v0113(boolean,boolean,boolean,boolean,boolean) to authenticated;
grant execute on function public.upsert_push_subscription_v0113(text,text,text,text) to authenticated;
grant execute on function public.remove_push_subscription_v0113(text) to authenticated;
grant execute on function public.count_my_push_subscriptions_v0113() to authenticated;
grant execute on function public.mark_notification_read_v0113(uuid) to authenticated;
grant execute on function public.mark_all_notifications_read_v0113() to authenticated;

-- ============================================================
-- 6. GERAÇÃO DE EVENTOS DA CENTRAL
-- ============================================================

create or replace function public.notification_push_allowed_v0113(target_user uuid, target_type text)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare p public.notification_preferences%rowtype;
begin
  select * into p from public.notification_preferences where user_id = target_user;
  if not found then
    return target_type in ('assignment','transfer');
  end if;
  if not p.push_enabled then return false; end if;
  return case target_type
    when 'assignment' then p.push_assignments
    when 'transfer' then p.push_transfers
    when 'status' then p.push_status
    when 'deadline' then p.push_deadlines
    else false
  end;
end
$$;

create or replace function public.create_user_notification_v0113(
  target_user uuid,
  target_workspace uuid,
  target_type text,
  target_severity text,
  target_title text,
  target_body text,
  target_movement bigint,
  target_process_number text,
  target_actor uuid,
  request_push boolean default false,
  extra_payload jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare notification_id uuid;
declare target_workspace_name text;
begin
  if target_user is null or target_workspace is null then return null; end if;
  if target_actor is not null and target_user = target_actor then return null; end if;
  if not exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = target_workspace and wm.user_id = target_user and wm.active
  ) then return null; end if;

  select w.name into target_workspace_name from public.workspaces w where w.id = target_workspace;

  insert into public.user_notifications(
    recipient_user_id, workspace_id, workspace_name, notification_type, severity,
    title, body, movement_id, process_number, actor_user_id, push_requested, payload
  ) values(
    target_user, target_workspace, coalesce(target_workspace_name,'Procuradoria'),
    target_type, target_severity, target_title, target_body,
    target_movement, coalesce(target_process_number,''), target_actor,
    coalesce(request_push,false) and public.notification_push_allowed_v0113(target_user,target_type),
    coalesce(extra_payload,'{}'::jsonb)
  ) returning id into notification_id;

  return notification_id;
end
$$;

revoke execute on function public.notification_push_allowed_v0113(uuid,text) from public, anon, authenticated;
revoke execute on function public.create_user_notification_v0113(uuid,uuid,text,text,text,text,bigint,text,uuid,boolean,jsonb) from public, anon, authenticated;

create or replace function public.notify_movement_change_v0113()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare actor uuid;
declare process_number text;
declare process_label text;
begin
  actor := coalesce(auth.uid(), new.updated_by, new.created_by);
  select c.judicial_number into process_number from public.cases c where c.id = new.case_id;
  process_label := case when trim(coalesce(process_number,'')) <> '' then process_number else 'sem número informado' end;

  if tg_op = 'INSERT' then
    if new.assigned_to is not null then
      perform public.create_user_notification_v0113(
        new.assigned_to, new.workspace_id, 'assignment',
        case when new.priority = 'Urgente' then 'urgent' else 'info' end,
        'Novo processo atribuído',
        'O processo ' || process_label || ' foi atribuído a você.',
        new.id, process_number, actor, true,
        jsonb_build_object('priority',new.priority,'workflow_status',new.workflow_status)
      );
    end if;
    return new;
  end if;

  -- Transferência entre Procuradorias: um único evento específico para o novo responsável.
  if old.workspace_id is distinct from new.workspace_id then
    if new.assigned_to is not null then
      perform public.create_user_notification_v0113(
        new.assigned_to, new.workspace_id, 'transfer', 'warning',
        'Processo transferido para sua Procuradoria',
        'O processo ' || process_label || ' foi transferido e atribuído a você.',
        new.id, process_number, actor, true,
        jsonb_build_object('source_workspace_id',old.workspace_id,'target_workspace_id',new.workspace_id)
      );
    end if;
    return new;
  end if;

  if old.assigned_to is distinct from new.assigned_to and new.assigned_to is not null then
    perform public.create_user_notification_v0113(
      new.assigned_to, new.workspace_id, 'assignment',
      case when new.priority = 'Urgente' then 'urgent' else 'info' end,
      'Processo atribuído a você',
      'O processo ' || process_label || ' foi redistribuído para sua fila.',
      new.id, process_number, actor, true,
      jsonb_build_object('previous_assignee',old.assigned_to)
    );
  end if;

  if old.workflow_status is distinct from new.workflow_status and new.assigned_to is not null then
    perform public.create_user_notification_v0113(
      new.assigned_to, new.workspace_id, 'status', 'info',
      'Status processual atualizado',
      'O processo ' || process_label || ' passou de “' || coalesce(old.workflow_status,'') || '” para “' || coalesce(new.workflow_status,'') || '”.',
      new.id, process_number, actor, true,
      jsonb_build_object('old_status',old.workflow_status,'new_status',new.workflow_status)
    );
  end if;

  if old.deadline_at is distinct from new.deadline_at and new.assigned_to is not null then
    perform public.create_user_notification_v0113(
      new.assigned_to, new.workspace_id, 'deadline', 'warning',
      'Prazo processual atualizado',
      case when new.deadline_at is null
        then 'O prazo do processo ' || process_label || ' foi removido.'
        else 'O prazo do processo ' || process_label || ' foi alterado para ' || to_char(new.deadline_at,'DD/MM/YYYY') || '.'
      end,
      new.id, process_number, actor, true,
      jsonb_build_object('old_deadline',old.deadline_at,'new_deadline',new.deadline_at)
    );
  end if;

  return new;
exception when others then
  -- Central/Push são subsistemas auxiliares: falhas nunca podem abortar a operação processual.
  return new;
end
$$;

revoke execute on function public.notify_movement_change_v0113() from public, anon, authenticated;

drop trigger if exists movement_notifications_v0113 on public.movements;
create trigger movement_notifications_v0113
after insert or update of assigned_to, workspace_id, workflow_status, deadline_at
on public.movements
for each row execute function public.notify_movement_change_v0113();

-- ============================================================
-- 7. ENFILEIRAMENTO E DISPARO ASSÍNCRONO
-- ============================================================

create or replace function public.queue_notification_push_v0113()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare cfg public.push_runtime_v0113%rowtype;
declare queued_count integer := 0;
begin
  if not new.push_requested then return new; end if;

  insert into public.push_deliveries(notification_id, subscription_id)
  select new.id, s.id
  from public.push_subscriptions s
  where s.user_id = new.recipient_user_id and s.enabled
  on conflict(notification_id, subscription_id) do nothing;
  get diagnostics queued_count = row_count;

  if queued_count > 0 then
    select * into cfg from public.push_runtime_v0113 where singleton = true;
    if cfg.dispatch_url is not null and cfg.dispatch_token is not null then
      perform net.http_post(
        url := cfg.dispatch_url,
        headers := jsonb_build_object('Content-Type','application/json'),
        body := jsonb_build_object('dispatch_token',cfg.dispatch_token::text),
        timeout_milliseconds := 5000
      );
    end if;
  end if;

  return new;
exception when others then
  -- Falha de entrega Push nunca pode abortar a operação processual nem a Central.
  return new;
end
$$;

revoke execute on function public.queue_notification_push_v0113() from public, anon, authenticated;

drop trigger if exists user_notifications_push_queue_v0113 on public.user_notifications;
create trigger user_notifications_push_queue_v0113
after insert on public.user_notifications
for each row execute function public.queue_notification_push_v0113();

-- A Edge Function usa Service Role e recebe lotes atomizados via SKIP LOCKED.
create or replace function public.claim_push_deliveries_v0113(
  target_user uuid default null,
  batch_limit integer default 50
)
returns table(
  delivery_id bigint,
  subscription_id uuid,
  endpoint text,
  p256dh text,
  auth_secret text,
  notification_id uuid,
  recipient_user_id uuid,
  workspace_id uuid,
  movement_id bigint,
  notification_type text,
  severity text,
  title text,
  body text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with candidates as (
    select d.id
    from public.push_deliveries d
    join public.user_notifications n on n.id = d.notification_id
    join public.push_subscriptions s on s.id = d.subscription_id and s.enabled
    where ((d.state = 'queued' and d.next_attempt_at <= now())
        or (d.state = 'processing' and d.claimed_at < now() - interval '10 minutes'))
      and (target_user is null or n.recipient_user_id = target_user)
    order by d.id
    for update of d skip locked
    limit greatest(1,least(coalesce(batch_limit,50),100))
  ), claimed as (
    update public.push_deliveries d
       set state = 'processing', claimed_at = now(), attempts = d.attempts + 1
      from candidates c
     where d.id = c.id
    returning d.id, d.notification_id, d.subscription_id
  )
  select
    c.id, s.id, s.endpoint, s.p256dh, s.auth_secret,
    n.id, n.recipient_user_id, n.workspace_id, n.movement_id,
    n.notification_type, n.severity, n.title, n.body
  from claimed c
  join public.user_notifications n on n.id = c.notification_id
  join public.push_subscriptions s on s.id = c.subscription_id;
end
$$;

create or replace function public.complete_push_delivery_v0113(
  target_delivery bigint,
  succeeded boolean,
  permanent_failure boolean default false,
  error_message text default ''
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare target_subscription uuid;
declare attempt_count integer;
begin
  select subscription_id, attempts into target_subscription, attempt_count
  from public.push_deliveries where id = target_delivery for update;
  if target_subscription is null then return; end if;

  if succeeded then
    update public.push_deliveries
       set state = 'sent', sent_at = now(), last_error = ''
     where id = target_delivery;
    update public.push_subscriptions
       set failure_count = 0, last_error = '', last_seen_at = now(), updated_at = now()
     where id = target_subscription;
  elsif permanent_failure then
    update public.push_deliveries
       set state = 'failed', last_error = left(coalesce(error_message,''),1000)
     where id = target_delivery;
    update public.push_subscriptions
       set enabled = false,
           failure_count = failure_count + 1,
           last_error = left(coalesce(error_message,''),1000),
           updated_at = now()
     where id = target_subscription;
  else
    update public.push_deliveries
       set state = case when coalesce(attempt_count,0) >= 5 then 'failed' else 'queued' end,
           next_attempt_at = now() + make_interval(mins => least(60, greatest(2, coalesce(attempt_count,1) * 5))),
           last_error = left(coalesce(error_message,''),1000)
     where id = target_delivery;
    update public.push_subscriptions
       set failure_count = failure_count + 1,
           last_error = left(coalesce(error_message,''),1000),
           updated_at = now()
     where id = target_subscription;
  end if;
end
$$;

revoke execute on function public.claim_push_deliveries_v0113(uuid,integer) from public, anon, authenticated;
revoke execute on function public.complete_push_delivery_v0113(bigint,boolean,boolean,text) from public, anon, authenticated;
grant execute on function public.claim_push_deliveries_v0113(uuid,integer) to service_role;
grant execute on function public.complete_push_delivery_v0113(bigint,boolean,boolean,text) to service_role;

commit;
