import { Database, Download, Globe2, History, Mail, ShieldCheck, Smartphone, WifiOff } from "lucide-react";
import { PRAXIS_BUILD, shortCommit } from "../buildInfo";
import { isStandaloneMode } from "../pwa";
import { PRAXIS_VERSION } from "../version";

const VERSIONS = [
  { version:"0.10.8.0", title:"Múltiplas Procuradorias de Justiça", items:["Seletor global permite alternar a Procuradoria ativa sem misturar dados entre unidades","Administrador pode cadastrar Procuradorias e habilitar usuários já cadastrados com perfil próprio em cada unidade","Visão Geral, Minha Fila, Processos, Eficiência e Relatórios ficam limitados à Procuradoria selecionada","Transferência administrativa move processos entre Procuradorias com novo responsável, justificativa e auditoria","RLS reforçado limita os dados operacionais ao workspace ativo"] },
  { version:"0.10.7.9", title:"Carga operacional e preparação multi-Procuradoria", items:["Abertura carrega apenas processos ativos e campos operacionais essenciais","Arquivados e campos detalhados passam a ser buscados somente quando necessários","Cache de movimentações é isolado pelo par usuário + Procuradoria","Equipe fica restrita ao workspace ativo e APIs de troca segura ficam preparadas para a 0.10.8"] },
  { version:"0.10.7.8", title:"Carregamento coordenado e telemetria", items:["Atualizações simultâneas reutilizam a mesma carga de movimentações","Pull-to-refresh atualiza somente os processos, sem repetir dados estruturais","Telemetria identifica motivo, página e quantidade de linhas da carga","Tempo de transformação e reaproveitamento de chamadas passam a ser distinguíveis"] },
  { version:"0.10.7.7", title:"Segurança do banco e retenção técnica", items:["Endurecimento das funções SECURITY DEFINER e bloqueio de execução anônima","MFA efetivo nas operações administrativas sensíveis","Workspace atual validado nas RPCs e responsável restrito à equipe ativa","Aceite de convites protegido contra concorrência e divergência de e-mail","Limpeza administrativa de erros e métricas técnicas com mais de 15 dias"] },
  { version:"0.10.7.6", title:"Comparativo responsivo e prioridades processuais", items:["Comparativo anual reorganizado conforme a largura real do painel","Gráfico e tabela protegidos contra sobreposição em orientação vertical","Urgência da fila separada da prioridade processual","Prioridades para pessoa idosa, pessoa com 80 anos ou mais, ECA e doença grave","Prioridade processual registrada no histórico e incluída nas exportações"] },
  { version:"0.10.7.5", title:"Redefinição administrativa de senha", items:["Redefinição de senha transferida para a função administrativa protegida","Validação do administrador, autenticação forte e vínculo do usuário no Supabase","Confirmação de envio e mensagens de falha exibidas no modal de edição","Solicitação registrada na auditoria administrativa"] },
  { version:"0.10.7.4", title:"Leitura da fila e gestos móveis", items:["Status Enviado destacado com o azul-marinho da identidade","Prazos inferiores a cinco dias destacados em vermelho sóbrio","Filtros reorganizados em Ano, Responsável, Status e Destacados","Swipe para a esquerda fecha o menu móvel","Justificativa da alteração da entrada exibida junto ao campo, sem bloqueio silencioso do botão Salvar"] },
  { version:"0.10.7.3", title:"Ajustes móveis e classes recursais", items:["Menu móvel posicionado abaixo da área segura do iPhone","Pull-to-refresh exibido somente ao atingir o ponto de atualização","Botões de colar no cadastro e botões de copiar preservados na edição","Classe/assunto legível na Minha fila móvel","Recurso Especial e Recurso Extraordinário disponíveis no cadastro e na edição"] },
  { version:"0.10.7.2", title:"Seletores e histórico de versões", items:["Listas suspensas alinhadas à altura dos campos de texto","Seletores compactos das tabelas ampliados sem aumentar excessivamente as linhas","Histórico da aba Sobre limitado às três versões mais recentes","Nomes e descrições das versões centralizados"] },
  { version:"0.10.7.1", title:"Correções visuais da identidade", items:["Menu móvel restrito a telas pequenas","Símbolos claro e escuro alinhados no menu recolhido","Botões de copiar compactos sem ampliar as linhas","Campos de Configurações e Equipe novamente padronizados","Classificações especiais e dados bloqueados corrigidos no modo escuro"] },
  { version:"0.10.7", title:"Mobile, operações em lote e nova identidade", items:["Gestos móveis, pull-to-refresh, feedback tátil e retorno ao topo","Cabeçalho responsivo com áreas de toque acessíveis","Histórico próprio e detalhado por processo","Seleção múltipla com responsável, intervenção, exportação, arquivamento e exclusão","Indicadores da Visão Geral clicáveis e novo Movimento Mensal comparativo","Nova identidade visual, ícones PWA, favicon, splash e estados vazios"] },
  { version:"0.10.6", title:"Otimização de desempenho", items:["Cálculo acelerado de horas úteis em históricos extensos","Redução das chamadas repetidas ao Supabase","Índice específico para a carga dos processos ativos","Atualização de providência e histórico em uma única operação","Diagnóstico separado entre busca e transformação dos dados"] },
  { version:"0.10.5", title:"Desempenho, robustez e experiência móvel", items:["Lazy loading das páginas e redução do bundle inicial","Carregamento sob demanda de PDF, planilhas e gráficos","Correção da tela inicial no celular e revisão das safe areas do iPhone","Fallback visual para páginas assíncronas e preservação do Error Boundary global","Revisão do workflow de qualidade, auditoria e dependências"] },
  { version:"0.10.3.4", title:"Passkey administrativa no backend", items:["RPCs e políticas administrativas aceitam passkey como autenticação forte","Auditoria, diagnóstico e logs técnicos liberados após login biométrico","Login por senha continua exigindo TOTP para acesso administrativo"] },
  { version:"0.10.3.3", title:"Passkey administrativa e acesso simplificado", items:["Auditoria e diagnóstico liberados por passkey","Reconhecimento ampliado de WebAuthn no JWT","Configuração biométrica transferida para Configurações","Login por senha ocultado após selecionar biometria"] },
  { version:"0.10.3.2", title:"Autenticação forte administrativa", items:["Passkey libera todas as funções administrativas","Senha continua protegida por TOTP","Operações destrutivas permitem confirmar por passkey ou código do autenticador"] },
  { version:"0.10.3.1", title:"Biometria sem código adicional", items:["Login por passkey dispensa o código TOTP","Login por e-mail e senha continua exigindo autenticação em duas etapas","Decisão baseada no método passkey assinado no JWT do Supabase","Sem uso de localStorage como critério de segurança"] },
  { version:"0.10.3", title:"PWA, biometria e desempenho", items:["Instalação como aplicativo no Mac e celulares","Service Worker, funcionamento do shell sem conexão e atualização automática","Acesso opcional por Face ID, Touch ID ou biometria do celular","Preferência biométrica restrita ao navegador selecionado","Consultas de movimentações em menos etapas e sem validações repetidas de sessão","Pré-carregamento paralelo e seleção reduzida de campos"] },
  { version:"0.10.2", title:"Importação Inteligente e desempenho", items:["Prévia detalhada antes da gravação","Importações por lote com histórico e reversão segura","Origem e precisão dos dados importados","Atualização incremental após cadastro e edição","Exportação e arquivamento das operações lentas","Botões para copiar números judiciais e MP","Legibilidade ampliada na Qualidade dos dados"] },
  { version:"0.10.1", title:"Auditoria, diagnóstico e refinamentos", items:["Auditoria e diagnóstico unificados","Ajuda contextual","Histórico de versões","Natureza da atuação com tooltip","Correção dos cartões de classificação especial","Integração das configurações nos relatórios"] },
  { version:"0.10.0", title:"Confiabilidade e engenharia", items:["Error Boundary","Captura global de erros","Logs técnicos seguros","Identificação de compilação","Testes e workflow de qualidade"] },
  { version:"0.9.5", title:"Integração e acabamento", items:["Configurações institucionais dos relatórios","Melhorias dos modais","Disclaimer de uso privado","Períodos de relatório revisados"] },
  { version:"0.9.0", title:"Governança e permissões", items:["Perfis e controle de acesso","Calendário por ano","Fechamento mensal","Configurações administrativas"] },
];

export function AboutPage() {
  const installed = isStandaloneMode();
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">Informações do aplicativo</p><h1>Sobre</h1><p>Autoria, finalidade, ambiente, evolução e informações do Práxis.</p></div></div>
    <section className="panel about-card"><img className="about-logo about-logo-light" src="/brand/logo-horizontal-light.webp" alt="Práxis - Controle de Processos" /><img className="about-logo about-logo-dark" src="/brand/logo-horizontal-dark.webp" alt="Práxis - Controle de Processos" /><div className="about-version">Práxis Web · Versão {PRAXIS_VERSION}</div><div className="build-metadata"><span><strong>Compilação</strong>{shortCommit()}</span><span><strong>Publicação</strong>{new Intl.DateTimeFormat("pt-BR", { dateStyle:"short", timeStyle:"short" }).format(new Date(PRAXIS_BUILD.publishedAt))}</span></div>
      <div className="about-copy"><p><strong>© 2026 Marcos Antonio Santos Machado. Todos os direitos reservados.</strong></p><p>Idealização e criação: Marcos Antonio Santos Machado.</p><p>Desenvolvido com assistência do ChatGPT/OpenAI.</p></div>
      <div className="about-purpose about-disclaimer"><h2>Natureza e finalidade de uso</h2><p>O Práxis Web é uma ferramenta privada de apoio à organização e ao controle pessoal de processos, criada sem finalidade comercial, lucrativa ou institucional. Seu uso é restrito ao criador e às pessoas por ele expressamente autorizadas.</p><p>O software não integra, não representa e não substitui sistemas oficiais do Ministério Público, do Poder Judiciário ou de qualquer outra instituição. Não se destina à distribuição pública, cessão, revenda, comercialização ou exploração econômica.</p><p>Os dados, prazos, indicadores e relatórios possuem caráter exclusivamente auxiliar e devem ser conferidos nos sistemas oficiais. O acesso, a reprodução, a disponibilização ou o uso por terceiros dependem de autorização expressa do criador.</p></div>
      <div className="about-purpose"><h2>Aplicativo instalável</h2><div className="pwa-about-grid"><span><Download />{installed ? "Práxis instalado neste dispositivo" : "Instalação disponível pelo navegador"}</span><span><Smartphone />Janela própria no Mac e no celular</span><span><WifiOff />Tela de contingência sem conexão</span><span><ShieldCheck />Dados processuais não são armazenados pelo Service Worker</span></div><p className="muted">Quando a instalação automática estiver disponível, o Práxis mostrará o botão “Instalar”. No iPhone e iPad, use Compartilhar → Adicionar à Tela de Início. No Safari do Mac, use Arquivo → Adicionar ao Dock.</p></div>
      <div className="about-purpose"><h2>Informações do ambiente</h2><div className="environment-grid"><span><Globe2 />Aplicação on-line/PWA</span><span><Database />PostgreSQL no Supabase</span><span><ShieldCheck />Autenticação, passkeys e RLS</span><span>Fuso: America/Belem</span></div></div>
      <div className="about-purpose version-history"><div className="title-with-help"><h2>Histórico de versões</h2><History size={19}/></div>{VERSIONS.slice(0, 3).map((release,index)=><details key={release.version} open={index===0}><summary><span><strong>Versão {release.version}</strong><small>{release.title}</small></span></summary><ul>{release.items.map(item=><li key={item}>{item}</li>)}</ul></details>)}</div>
      <a className="about-email" href="mailto:marcosmachado@mppa.mp.br"><Mail size={18}/>marcosmachado@mppa.mp.br</a>
    </section></div>;
}
