-- Práxis Web 0.9.0 — governança, perfis e controle de acesso
-- Execute integralmente no SQL Editor do Supabase.

alter type public.praxis_role add value if not exists 'estagiario';

begin;
alter table public.workspace_members add column if not exists efficiency_access text not null default 'own';
alter table public.workspace_members add column if not exists reports_access text not null default 'own';
do $$ begin alter table public.workspace_members add constraint workspace_members_efficiency_access_check check (efficiency_access in ('none','own','team')); exception when duplicate_object then null; end $$;
do $$ begin alter table public.workspace_members add constraint workspace_members_reports_access_check check (reports_access in ('none','own','team')); exception when duplicate_object then null; end $$;
update public.workspace_members set efficiency_access=case when role in ('admin','procurador') then 'team' when role::text in ('estagiario','consulta') then 'none' else coalesce(efficiency_access,'own') end, reports_access=case when role in ('admin','procurador') then 'team' when role::text in ('estagiario','consulta') then 'none' else coalesce(reports_access,'own') end;

create table if not exists public.workspace_settings(
 workspace_id uuid primary key references public.workspaces(id) on delete cascade,
 workday_hours numeric not null default 6 check(workday_hours between 1 and 12), workday_start time not null default '08:00', workday_end time not null default '14:00',
 default_deadline_business_days integer not null default 30 check(default_deadline_business_days between 1 and 365), count_from_next_business_day boolean not null default true,
 after_hours_policy text not null default 'next_business_day' check(after_hours_policy in ('keep','next_business_day')), unit_name text not null default '', lead_prosecutor text not null default '', report_footer text not null default '',
 default_report_mode text not null default 'executive' check(default_report_mode in ('executive','complete','highlights')), default_report_period text not null default 'year' check(default_report_period in ('month','30days','year')),
 allow_named_comparisons boolean not null default false, require_action_on_send boolean not null default true, require_assignee_on_progress boolean not null default true, detect_duplicates boolean not null default true,
 require_date_change_reason boolean not null default true, block_closed_periods boolean not null default true, updated_at timestamptz not null default now());
insert into public.workspace_settings(workspace_id) select id from public.workspaces on conflict do nothing;

create table if not exists public.closed_periods(
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade, year integer not null, month integer not null check(month between 1 and 12),
 closed_at timestamptz not null default now(), closed_by uuid references public.profiles(id), reason text not null, reopened_at timestamptz, reopened_by uuid references public.profiles(id), reopen_reason text not null default '', unique(workspace_id,year,month));

create or replace function public.current_workspace_role(target_workspace uuid) returns text language sql stable security definer set search_path=public as $$select role::text from public.workspace_members where workspace_id=target_workspace and user_id=auth.uid() and active limit 1$$;
create or replace function public.can_view_case_v09(target_workspace uuid,target_case bigint) returns boolean language sql stable security definer set search_path=public as $$select case when public.current_workspace_role(target_workspace)='estagiario' then exists(select 1 from public.movements where workspace_id=target_workspace and case_id=target_case and assigned_to=auth.uid()) else public.is_workspace_member(target_workspace) end$$;

create or replace function public.list_current_workspace_members_v09() returns table(user_id uuid,full_name text,email text,role public.praxis_role,active boolean,mfa_required boolean,historico_disponivel_desde date,efficiency_access text,reports_access text) language sql stable security definer set search_path=public as $$
 select wm.user_id,p.full_name,coalesce(u.email,''),wm.role,wm.active,coalesce((u.raw_user_meta_data->>'mfa_required')::boolean,false),wm.historico_disponivel_desde,
 case when wm.role in ('admin','procurador') then 'team' when wm.role::text in ('estagiario','consulta') then 'none' else wm.efficiency_access end,
 case when wm.role in ('admin','procurador') then 'team' when wm.role::text in ('estagiario','consulta') then 'none' else wm.reports_access end
 from public.workspace_members wm join public.profiles p on p.id=wm.user_id join auth.users u on u.id=wm.user_id
 where wm.workspace_id in(select workspace_id from public.workspace_members where user_id=auth.uid() and active) order by p.full_name$$;

create or replace function public.update_workspace_member_access_v09(target_user uuid,new_efficiency_access text,new_reports_access text) returns void language plpgsql security definer set search_path=public as $$declare ws uuid;target_role text;begin
 select workspace_id into ws from public.workspace_members where user_id=auth.uid() and active and role='admin' limit 1;if ws is null then raise exception 'Apenas o administrador pode alterar permissões.';end if;
 if new_efficiency_access not in('none','own','team') or new_reports_access not in('none','own','team') then raise exception 'Escopo inválido.';end if;
 select role::text into target_role from public.workspace_members where workspace_id=ws and user_id=target_user;
 update public.workspace_members set efficiency_access=case when target_role in('admin','procurador') then 'team' when target_role in('estagiario','consulta') then 'none' else new_efficiency_access end,reports_access=case when target_role in('admin','procurador') then 'team' when target_role in('estagiario','consulta') then 'none' else new_reports_access end where workspace_id=ws and user_id=target_user;
end$$;

create or replace function public.guard_movement_v09() returns trigger language plpgsql security definer set search_path=public as $$declare r text;blocked boolean;oldj jsonb;newj jsonb;begin r:=public.current_workspace_role(coalesce(new.workspace_id,old.workspace_id));if r is null then raise exception 'Acesso negado.';end if;
 if tg_op='UPDATE' then select exists(select 1 from public.closed_periods cp join public.workspace_settings s on s.workspace_id=cp.workspace_id where cp.workspace_id=old.workspace_id and cp.year=extract(year from old.received_at at time zone 'America/Belem') and cp.month=extract(month from old.received_at at time zone 'America/Belem') and cp.reopened_at is null and s.block_closed_periods) into blocked;if blocked and r<>'admin' then raise exception 'O período está fechado.';end if;
 if r<>'admin' and (new.received_at is distinct from old.received_at or new.received_time_precise is distinct from old.received_time_precise) then raise exception 'Somente o administrador pode alterar a entrada.';end if;
 if r='estagiario' then if old.assigned_to<>auth.uid() then raise exception 'O estagiário só pode alterar processos atribuídos a ele.';end if;oldj:=to_jsonb(old)-array['workflow_status','action_type','notes','draft_status','sent_at','sent_time_precise','elapsed_hours','updated_by','updated_at','row_version'];newj:=to_jsonb(new)-array['workflow_status','action_type','notes','draft_status','sent_at','sent_time_precise','elapsed_hours','updated_by','updated_at','row_version'];if oldj<>newj then raise exception 'O estagiário só pode alterar status, providência e observação interna.';end if;end if;
 end if;return new;end$$;
drop trigger if exists guard_movement_v09_trigger on public.movements;create trigger guard_movement_v09_trigger before update on public.movements for each row execute function public.guard_movement_v09();

create or replace function public.update_movement_v09(target_movement bigint,payload jsonb,change_reason text default null) returns void language plpgsql security definer set search_path=public as $$declare ws uuid;r text;oldm public.movements;new_received timestamptz;new_sent timestamptz;begin select * into oldm from public.movements where id=target_movement;ws:=oldm.workspace_id;r:=public.current_workspace_role(ws);if r is null then raise exception 'Acesso negado.';end if;
 if r='estagiario' then update public.movements set notes=coalesce(payload->>'notes',notes),updated_by=auth.uid(),updated_at=now() where id=target_movement and assigned_to=auth.uid();return;end if;if r not in('admin','procurador','assessor') then raise exception 'Perfil sem permissão de edição.';end if;
 new_received=coalesce(nullif(payload->>'receivedAt','')::timestamptz,oldm.received_at);new_sent=nullif(payload->>'sentAt','')::timestamptz;
 if new_received is distinct from oldm.received_at and r<>'admin' then raise exception 'Somente o administrador pode alterar a entrada.';end if;if new_received is distinct from oldm.received_at and coalesce(trim(change_reason),'')='' then raise exception 'Informe a justificativa da alteração da entrada.';end if;
 update public.cases set class_name=coalesce(payload->>'className',class_name),subject=coalesce(payload->>'subject',subject),socially_relevant=coalesce((payload->>'sociallyRelevant')::boolean,socially_relevant),extremely_complex=coalesce((payload->>'extremelyComplex')::boolean,extremely_complex),social_theme=coalesce(payload->>'socialTheme',social_theme),relevance_reason=coalesce(payload->>'relevanceReason',relevance_reason),fundamental_right=coalesce(payload->>'fundamentalRight',fundamental_right),affected_group=coalesce(payload->>'affectedGroup',affected_group),reach=coalesce(payload->>'reach',reach),territorial_scope=coalesce(payload->>'territorialScope',territorial_scope),impact_type=coalesce(payload->>'impactType',impact_type),social_result=coalesce(payload->>'socialResult',social_result),complexity_reason=coalesce(payload->>'complexityReason',complexity_reason),updated_by=auth.uid(),updated_at=now() where id=oldm.case_id;
 update public.movements set received_at=new_received,received_time_precise=coalesce((payload->>'receivedTimePrecise')::boolean,received_time_precise),sent_at=case when r='admin' then new_sent else sent_at end,sent_time_precise=case when r='admin' then coalesce((payload->>'sentTimePrecise')::boolean,false) else sent_time_precise end,deadline_at=nullif(payload->>'deadlineAt','')::date,action_type=coalesce(payload->>'actionType',action_type),notes=coalesce(payload->>'notes',notes),priority=coalesce(payload->>'priority',priority),document_path=coalesce(payload->>'documentPath',document_path),assigned_to=coalesce(nullif(payload->>'assignedTo','')::uuid,assigned_to),updated_by=auth.uid(),updated_at=now() where id=target_movement;
 if new_received is distinct from oldm.received_at then insert into public.change_history(workspace_id,movement_id,changed_by,field_name,old_value,new_value) values(ws,target_movement,auth.uid(),'Justificativa da alteração de entrada',oldm.received_at::text||' | '||coalesce(change_reason,''),new_received::text);end if;end$$;

alter table public.workspace_settings enable row level security;

alter table public.closed_periods enable row level security;
drop policy if exists workspace_settings_select_member on public.workspace_settings;create policy workspace_settings_select_member on public.workspace_settings for select using(public.is_workspace_member(workspace_id));
drop policy if exists workspace_settings_write_admin on public.workspace_settings;create policy workspace_settings_write_admin on public.workspace_settings for all using(public.is_workspace_admin(workspace_id)) with check(public.is_workspace_admin(workspace_id));
drop policy if exists closed_periods_select_member on public.closed_periods;create policy closed_periods_select_member on public.closed_periods for select using(public.is_workspace_member(workspace_id));
drop policy if exists closed_periods_write_admin on public.closed_periods;create policy closed_periods_write_admin on public.closed_periods for all using(public.is_workspace_admin(workspace_id)) with check(public.is_workspace_admin(workspace_id));

drop policy if exists movements_select_member on public.movements;create policy movements_select_member on public.movements for select using(public.is_workspace_member(workspace_id) and (public.current_workspace_role(workspace_id)<>'estagiario' or assigned_to=auth.uid()));
drop policy if exists movements_insert_writer on public.movements;create policy movements_insert_writer on public.movements for insert with check(public.current_workspace_role(workspace_id) in('admin','procurador','assessor'));
drop policy if exists movements_update_writer on public.movements;create policy movements_update_writer on public.movements for update using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));
drop policy if exists cases_select_member on public.cases;create policy cases_select_member on public.cases for select using(public.can_view_case_v09(workspace_id,id));
drop policy if exists classes_insert_writer on public.class_settings;drop policy if exists classes_update_writer on public.class_settings;drop policy if exists classes_delete_admin on public.class_settings;create policy classes_admin_all on public.class_settings for all using(public.is_workspace_admin(workspace_id)) with check(public.is_workspace_admin(workspace_id));
drop policy if exists calendar_insert_writer on public.calendar_exclusions;drop policy if exists calendar_update_writer on public.calendar_exclusions;drop policy if exists calendar_delete_writer on public.calendar_exclusions;create policy calendar_admin_all on public.calendar_exclusions for all using(public.is_workspace_admin(workspace_id)) with check(public.is_workspace_admin(workspace_id));
commit;
